spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb_prod:3306/TRY_CATCH?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: S08P12E108
    password: LGBmz7o81b
    hikari:
      validation-timeout: 2000
      maximum-pool-size: 999

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 7b4fb4e472ba8a793c1b
            client-secret: 4f5672997fa38b23f9d8641f85cd1ea3cca44abf
            redirect-uri: https://api.try-catch.duckdns.org/login/oauth2/code/github
            scope:
              - user:email
              - read:user
              - repo

elasticsearch:
  index:
    prefix: prod

settings:
  cross-origin: >
    https://try-catch.kr

  login:
    on_success:
      redirect_uri: https://try-catch.kr
    on_fail:
      redirect_uri: https://try-catch.kr/error


apiPrefix:
  v1