GET localhost:8080/v1/user/name
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnaG9fYUwwWVdzdm9zaVVPYnFmR2hFdzRZVVRRZnJFSGFkMDhLQ0RmIiwiaWQiOiI0IiwiaWF0IjoxNjc1NjA1OTA1LCJleHAiOjE2NzU2NDkxMDV9.myJLgCAAHmtPCqHsAO6nKzSTMyQaO18Iio06AHuqmlc\
Refresh: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnaG9feFlBdUphSG1WVXZPdmJFcnJ2bWQ3ekMyR2ZQVFdDMnY0TlpwIiwiaWQiOiIzIiwiaWF0IjoxNjc1MzE1MTE0LCJleHAiOjE2NzU0MDE1MTR9.t94fNgs72El0k8KMsn1fcgWwEIRF60lkBkwftpdKBvc

###
POST try-catch.duckdns.org:8000/doc2vec
Content-Type: application/json

{
  "doc": "나는 파이썬이 좋아요"
}